# Site settings
title: Slate
tagline: By Pixelarity
description: > # this means to ignore newlines until "baseurl:"
  Benjamin GUILLAUME : Présentation de mes compétences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://benjamin-guillaume.github.io" # the base hostname & protocol for your site

# Plugins
gems: ["jekyll-paginate"]

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

# Pagination
paginate: 4
paginate_path: "/blog/page:num/"

encoding: utf8

timezone: Europe/Paris